### ISSUE TITLE
Having the mod installed causes PBS Slice Metallic to be replaced by PBS Slice Specular

### ISSUE THREAD

**Issue by Dusty-Sprinkles** [EIA485/NeosMoreReferenceProxies#2]
Yea,  its on 1387 and I discovered this fun fact earlier today trying to make slice metallics.

removing the mod fixed it

Didn't check if it was both the material create new and normal one, but the first broke for sure

just realized this hasn't been updated since 2022 so I maybe submitted to the wrong repo

**Comment by Dusty-Sprinkles** [comment]
noticed that it was apparently depricated so closing (also wasn't this one)

**Comment by EIA485** [comment]
its not deprecated necessarily. are you using neos or resonite? I have absolutely no clue how this mod could cause the issue you are reporting. id be shocked if you still encountered the reported issue still happened with no other mods present.

**Comment by Dusty-Sprinkles** [comment]
Resonite, the issue was specifically with a fork of this called ResoniteMoreReferenceProxies, and at least according to the dev of that specific mod its basically fully implemented ingame

It did go away when I removed it so I assume it was that mod causing it (though possibly through a chain reaction of problems if it wasn't directly its fault)

Either way its mostly unrelated to this branch which is probably reason enough to close it

**Comment by EIA485** [comment]
gotchya. yeah if you have a problem with a fork id suggest creating an issue within said fork. you can probably use this use this branch via [EIA485/resonoseCompatWedge](https://github.com/EIA485/resonoseCompatWedge)
